service: mediapp

frameworkVersion: "4"

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  environment:
    REGION: ${self:provider.region}
    MEDICAMENTS_TABLE: MedicamentsTable
    REMINDERS_TABLE: RemindersTable
    USERS_TABLE: UsersTable
    ADMINS_TABLE: AdminsTable
    RECOMMENDATIONS_TABLE: RecommendationsTable
    AWS_S3_BUCKET_NAME: mediapp 

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query" 
        - "dynamodb:Scan"
        - "dynamodb:BatchWriteItem"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"


      ## Permissions to all tables in the region
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/*/index/*"
        - "arn:aws:s3:::${self:provider.environment.AWS_S3_BUCKET_NAME}/*"

functions: ${file(./functions.yml):functions}

resources:
  Resources: ${file(./resources.yml):resources}
